#!/bin/sh
basedir=$(dirname $0)

. ${basedir}/../../release_versioning

crayversion=
branch=
if [ ! -z ${build_number} ]; then
 # This version was built from a non-release branch
  crayversion="${common_tool_major:-0}.${common_tool_minor:-0}.${revision:-0}.${build_number}"
  branch="master"
else
  # This version was built from a release branch
  crayversion="${common_tool_major:-0}.${common_tool_minor:-0}.${revision:-0}"
  branch="release"
fi

cdstsupportversionmin=$(echo ${CRAY_CDST_SUPPORT_VERSION} | awk -F . '{ print $1"."$2 }')
tmpver=$(echo ${CRAY_CDST_SUPPORT_VERSION} | awk -F . '{ print $1 }')
cdstsupportversionmax=$(($tmpver+1))

dyninstrev=$(echo ${CRAY_DYNINST_VERSION} | awk -F . '{ print $3 }')
dyninstversionmin=$(echo ${CRAY_DYNINST_VERSION} | awk -F . '{ print $1"."$2 }')
if [ "$dyninstversionmin" = 12.3 -a "$dyninstrev" -ge 6 ]; then
    # cray-dyninst 12.3.6 moved dependent libraries out of cdst-support into dyninst
    # 12.3 matches the upstream version, so we need to use the rev for 12.3.x
    dyninstversionmin=12.3.6
fi

tmpver=$(echo ${CRAY_DYNINST_VERSION} | awk -F . '{ print $1 }')
dyninstversionmax=$(($tmpver+1))

arguments=$(getopt -o csm --long crayversion,cdstversionmin,cdstversionmax,cdstsupportversionmin,dyninstversionmin,dyninstversionmax,branch -n ${0} -- "$@")

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

while true ; do
    case "$1" in
        -c|--crayversion) echo "${crayversion}" ; shift ;;
        -s|--cdstversionmin) echo "${cdstsupportversionmin}" ; shift ;;
        -m|--cdstversionmax) echo "${cdstsupportversionmax}" ; shift ;;
        -d|--dyninstversionmin) echo "${dyninstversionmin}" ; shift ;;
        -f|--dyninstversionmax) echo "${dyninstversionmax}" ; shift ;;
        -b|--branch) echo "${branch}" ; shift ;;
        *) break ;;
    esac
done
