#!/bin/ksh
#
# MPT Man Page updating script
# Copyright 2004-2013 Cray Inc. All Rights Reserved.

. /opt/modules/default/init/ksh
module load craysvn

pubs_workdir=$PWD/tmp_pubs

if [ ! -d $pubs_workdir ]
then
  mkdir $pubs_workdir
fi

cd $pubs_workdir
  svn export http://svn/svn/pubs/tools/docbook-to-man/trunk/ tools
  cd tools
    aclocal
    automake --add-missing --gnu
    autoconf
    ./configure
    make
    export PATH=$PWD/Instant:$PATH
    svn export http://svn/svn/pubs/tools/doctools/bin/trunk/nsgmls
    export PATH=$PWD:$PATH
  cd ../

  svn export http://svn/svn/pubs/tools/perl-Pubs/trunk perl-Pubs
  svn export http://svn/svn/pubs/tools/xml2roff/trunk xml2roff
  
  export PERL5LIB=$PWD/perl-Pubs/lib

  cd xml2roff
    aclocal
    automake --add-missing --gnu
    autoconf
    ./configure x86_64-suse-linux --prefix=$PWD --exec-prefix=$PWD --with-catalogsdir=$PWD/catalogs --with-cmapdir=$PWD/cmap --with-declarationsdir=$PWD/declarations --with-dtddir=$PWD/dtd --with-sdatadir=$PWD/sdata --with-sgmldir=$PWD/ent --with-transpecdir=$PWD/transpec --with-tmacdir=$PWD/tmac
    make
    chmod 755 bin/xml2roff
    mkdir -p share/tmac/cray
    cp tmac/tmac.uc.2007.ship share/tmac/cray
    export PATH=$PWD/bin:$PATH
    cp ./sgml/iso-* ent/
  cd ../

  #svn co http://svn/svn/pubs/man/xe_libsmam/branches/60/man3/
  mkdir man1
  cd man1
    #svn export http://svn/svn/pubs/man/xe_mptm/branches/60/man3/intro_mpi.3.xml
    svn export http://svn/svn/pubs/man/xt_lgdbm/branches/21/man1/lgdb.1.xml
    for i in `ls *xml`
     do xml2roff -F $i
      test.roff `echo $i | sed "s/\.xml//g"`
      mklinks $i
      rm $i
     done
    rm -f README
  cd ..
  find ./man1/ -depth -print | cpio -o > lgdb_man_21.cpio
  
