# Copyright 2020 Hewlett Packard Enterprise Development LP.

CFLAGS = -Wall -g -O0

hello_mpi : hello_mpi.c
	cc $(CLAGS) $^ -o $@

hello_mpi_wait : hello_mpi_wait.c
	cc $(CLAGS) $^ -o $@

mpi_wrapper : mpi_wrapper.c
	cc $(CLAGS) $^ -o $@
